version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "type/dependencies"
      - "comp/github-actions"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
