import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]


class IOSAppScaffoldContractTest(unittest.TestCase):
    def test_shared_openai_lane_is_documented_and_guarded(self):
        policy = ROOT / "SHARED_OPENAI_LANE.md"
        script = ROOT / "scripts" / "shared_openai_synthetic_eval.py"
        agents = ROOT / "AGENTS.md"
        readme = ROOT / "README.md"
        self.assertTrue(policy.exists(), "shared OpenAI lane policy should exist")
        self.assertTrue(script.exists(), "synthetic eval script should exist")
        policy_text = policy.read_text()
        script_text = script.read_text()
        agents_text = agents.read_text()
        readme_text = readme.read_text()
        self.assertIn("OPENAI_SHARED_EVALS_API_KEY", policy_text)
        self.assertIn("HERMES_AGENT_SHARED_OPENAI_ALLOW=synthetic-only", policy_text)
        self.assertIn("Never send", readme_text)
        self.assertIn("live Hermes Agent chat transcripts", policy_text)
        self.assertIn("Hermes memory", policy_text)
        self.assertIn("Obsidian vault notes", policy_text)
        self.assertIn("screenshots", policy_text)
        self.assertIn("raw gateway WebSocket URLs containing tokens", policy_text)
        self.assertIn("never use `OPENAI_SHARED_EVALS_API_KEY`", agents_text)
        self.assertIn("SYNTHETIC_FIXTURE", script_text)
        self.assertIn("HERMES_AGENT_SHARED_OPENAI_ALLOW", script_text)
        self.assertIn("synthetic-only", script_text)
        self.assertNotIn("open('/Users", script_text)
        self.assertNotIn("Mobile Documents", script_text)
        self.assertNotIn(".hermes", script_text)

    def test_project_declares_native_ios_app_target(self):
        project = ROOT / "project.yml"
        self.assertTrue(project.exists(), "project.yml should define the generated Xcode project")
        text = project.read_text()
        self.assertIn("Hermes Agent iOS", text)
        self.assertIn("platform: iOS", text)
        self.assertIn("Hermes Agent iOS UI Tests", text)
        self.assertIn("bundle.ui-testing", text)
        self.assertIn("TEST_TARGET_NAME: Hermes Agent iOS", text)
        self.assertNotIn("DEVELOPMENT_TEAM:", text)
        self.assertNotIn("CODE_SIGNING_ALLOWED: NO", text)
        self.assertIn("type: application", text)
        self.assertIn("HermesAgentCore", text)

    def test_swiftui_app_shell_has_command_center_surfaces(self):
        app_file = ROOT / "App" / "HermesAgentIOSApp.swift"
        content_file = ROOT / "App" / "ContentView.swift"
        self.assertTrue(app_file.exists(), "SwiftUI @main app file should exist")
        self.assertTrue(content_file.exists(), "SwiftUI content view should exist")
        content = content_file.read_text()
        self.assertIn("Command Center", content)
        self.assertIn("Hermes Agent overview", content)
        self.assertIn("HERMES", content)
        self.assertIn("Hermes chat cockpit", content)
        self.assertIn("Chat", content)
        self.assertIn("Message HermesAgent", content)
        self.assertIn("Chat History", content)
        self.assertIn("HermesAgentChatTranscriptSnapshot", content)
        self.assertIn("hermesChatTranscriptJSON", content)
        self.assertIn("hermesRuntimeStoredSessionId", content)
        self.assertIn("loadPersistedChatTranscript", content)
        self.assertIn("persistChatTranscript", content)
        self.assertIn("New Chat", content)
        self.assertIn("Resumed ", content)
        self.assertIn("messages hydrated", content)
        self.assertIn("No remote sessions found on Hermes Desktop", content)
        self.assertIn("Remote session fetch unavailable: configure a Hermes Desktop gateway URL first.", content)
        self.assertIn("remoteSessionErrorMessage", content)
        self.assertIn("Hermes Desktop returned an RPC error", content)
        self.assertIn("hermesRuntimeStoredSessionTitle", content)
        self.assertIn("Remote Sessions", content)
        self.assertIn("Fetch Remote Sessions", content)
        self.assertIn("fetchRemoteSessions", content)
        self.assertIn("resumeRemoteSession", content)
        self.assertIn("Open operator menu", content)
        self.assertIn("HermesAgentChatLine", content)
        self.assertIn("HermesAgentChatBubble", content)
        self.assertIn("appendUserChatLine", content)
        self.assertIn("replacePendingAssistantChatLine", content)
        self.assertIn("replacePendingAssistantChatLine(with text: String, isPending: Bool = false)", content)
        self.assertIn("replacePendingAssistantChatLine(with: hermesRuntimeState.assistantText, isPending: !isTerminal)", content)
        self.assertIn("replacePendingAssistantChatLine(with: \"Hermes is working…\", isPending: true)", content)
        self.assertIn("if case .message = line.kind { return true }", content)
        self.assertNotIn("replacePendingAssistantChatLine(with: hermesRuntimeState.assistantText)\n", content)
        self.assertIn("HermesAgentToolActionsRow", content)
        self.assertIn("HermesAgentInlineBlockingRequestCard", content)
        self.assertIn("hermes-agent-inline-blocking-card", content)
        self.assertIn("hermes-agent-inline-blocking-answer-field", content)
        self.assertIn("hermes-agent-inline-blocking-primary-button", content)
        self.assertIn("respondToHermesBlockingRequest", content)
        self.assertIn("isRespondingHermesBlockingRequest", content)
        self.assertNotIn(".disabled(isWorking || (requiresTextInput", content)
        self.assertIn("SecureField(placeholder", content)
        self.assertIn("Value stays hidden in UI and transcript.", content)
        self.assertIn("HermesChatRuntimeReducer", content)
        self.assertIn("HermesGatewayRPCClient", content)
        self.assertIn("hermesGatewayWebSocketURL", content)
        self.assertIn("hermesGatewayRemoteBaseURL", content)
        self.assertIn("hermesGatewayRemoteWebSocketURL", content)
        self.assertIn("HermesGatewayRemoteConnection.webSocketURL", content)
        self.assertIn("percentEncodedQuery", (ROOT / "Sources" / "HermesAgentCore" / "HermesGatewayRemoteConnection.swift").read_text())
        self.assertIn("hermesGatewayWebSocketToken", content)
        self.assertIn("canUseHermesRuntimeChat", content)
        self.assertIn("isHermesRuntimeChatInProgress", content)
        self.assertIn("shouldShowBlockingProgressOverlay", content)
        ui_tests = (ROOT / "UITests" / "HermesAgentPhysicalLiveChatUITests.swift").read_text()
        self.assertIn("testHermesRuntimeTranscriptPersistsAfterRelaunch", ui_tests)
        self.assertIn("HERMES_AGENT_IOS_HISTORY_OK", ui_tests)
        self.assertIn("HERMES_AGENT_INLINE_CLARIFY_OK", ui_tests)
        self.assertIn("hermes-agent-inline-blocking-answer-field", ui_tests)
        self.assertIn("hermes-agent-blocking-progress-overlay", ui_tests)
        self.assertIn("isWorking && !isHermesRuntimeChatInProgress", content)
        self.assertIn("Hermes response requested…", content)
        self.assertIn("Hermes response streaming…", content)
        self.assertIn("Hermes chat runtime connected", content)
        self.assertIn("response.complete", content)
        self.assertIn("hermesRuntimeState.assistantText = \"\"", content)
        self.assertIn("hermesRuntimeState.toolGroup = nil", content)
        runtime = (ROOT / "Sources" / "HermesAgentCore" / "HermesGatewayRuntime.swift").read_text()
        self.assertIn("Tool actions", runtime)
        self.assertIn("thinking.delta", runtime)
        self.assertIn("HermesChatBlockingRequest", runtime)
        self.assertIn("approval.request", runtime)
        self.assertIn("clarify.request", runtime)
        self.assertIn("sudo.request", runtime)
        self.assertIn("secret.request", runtime)
        self.assertIn("respondToApproval", runtime)
        self.assertIn("sendNotification", runtime)
        self.assertIn("listSessions", runtime)
        self.assertIn("session.list", runtime)
        self.assertIn("resumeSession", runtime)
        self.assertIn("session.resume", runtime)
        self.assertIn("HermesRemoteSessionSummary", runtime)
        self.assertIn("HermesRemoteSessionResumeResponse", runtime)
        self.assertIn("parseSessionListResult", runtime)
        self.assertIn("parseSessionResumeResult", runtime)
        contract_tests = (ROOT / "Sources" / "HermesAgentCoreContractTest" / "main.swift").read_text()
        self.assertIn("session.list parser should accept id aliases", contract_tests)
        self.assertIn("session.resume parser should accept content aliases", contract_tests)
        self.assertIn("first\\n[image]\\n[audio]", contract_tests)
        self.assertIn("HermesGatewayRPCError.missingSessionId", contract_tests)
        self.assertIn("unknown age", runtime)
        self.assertIn("case \"message.delta\":", runtime)
        self.assertIn("case \"reasoning.delta\", \"thinking.delta\", \"reasoning.available\":", runtime)
        self.assertIn("next.isStreaming = true", runtime)
        self.assertIn("bufferedEvents", runtime)
        self.assertIn("currentTask.state", runtime)
        self.assertIn("case .running, .suspended", runtime)
        smoke = (ROOT / "scripts" / "smoke_hermes_gateway_ws.py").read_text()
        self.assertIn("session.create", smoke)
        self.assertIn("prompt.submit", smoke)
        self.assertIn("Token: <redacted>", smoke)
        self.assertNotIn("print(token", smoke)
        self.assertIn("HermesAgentDesktopStatusBar", content)
        self.assertIn("HermesAgentMobileShellStyle", content)
        self.assertIn("HermesAgentMobileShellCard", content)
        self.assertIn("HermesAgentStatusPill", content)
        self.assertIn("MobileShellSectionHeader", content)
        self.assertIn("Hermes ready", content)
        self.assertIn("Token missing", content)
        self.assertIn("Primary surfaces: Inbox · Command Composer · Needs Attention · Timeline · Diagnostics", content)
        self.assertIn("commandCenterSummary", content)
        self.assertIn("Inbox", content)
        self.assertIn("Command Composer", content)
        self.assertIn("Needs Attention", content)
        self.assertIn("Timeline", content)
        self.assertIn("Diagnostics", content)
        self.assertIn("HermesAgentCore", content)

    def test_app_uses_mock_gateway_default_base_url(self):
        settings_file = ROOT / "App" / "GatewaySettings.swift"
        self.assertTrue(settings_file.exists(), "Gateway settings should exist")
        settings = settings_file.read_text()
        self.assertIn("http://127.0.0.1:8787", settings)
        self.assertIn("GatewayClient", settings)

    def test_app_intents_v0_exposes_shortcuts_without_secret_rendering(self):
        intents_file = ROOT / "App" / "HermesAgentAppIntents.swift"
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        self.assertTrue(intents_file.exists(), "App Intents source should exist")
        intents = intents_file.read_text()
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("import AppIntents", intents)
        self.assertIn("AskHermesAgentIntent", intents)
        self.assertIn("RunLiveSmokeIntent", intents)
        self.assertIn("OpenNeedsAttentionIntent", intents)
        self.assertIn("CheckHermesCapabilityIntent", intents)
        self.assertIn("HermesAgentShortcutsProvider", intents)
        self.assertIn("openAppWhenRun", intents)
        self.assertIn("pendingAppIntentRoute", intents)
        self.assertIn("HermesAgentAppIntentRoute", core)
        self.assertIn("HermesAgentAppIntentKind", core)
        self.assertIn("isSecretSafeForDisplay", core)
        self.assertIn("Shortcuts / App Intents", content)
        self.assertIn("Apply Pending Shortcut", content)
        self.assertIn("applyPendingAppIntentRoute", content)
        self.assertIn("hermesRunCardFilter = .needsAttention", content)
        self.assertIn("Pending route: <redacted operator route>", content)
        self.assertNotIn("Text(pendingAppIntentRoute", content, "shortcut route should not render raw stored route")

    def test_share_extension_v0_hands_text_and_urls_to_app_without_secret_chrome(self):
        project_file = ROOT / "project.yml"
        share_source = ROOT / "ShareExtension" / "ShareViewController.swift"
        share_info = ROOT / "ShareExtension" / "Info.plist"
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        self.assertTrue(share_source.exists(), "Share Extension source should exist")
        self.assertTrue(share_info.exists(), "Share Extension Info.plist should exist")
        project = project_file.read_text()
        share = share_source.read_text()
        info = share_info.read_text()
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("Hermes Agent Share Extension", project)
        self.assertIn("com.tinyleed.hermes-agent-ios.share-extension", project)
        self.assertIn("APPLICATION_EXTENSION_API_ONLY: YES", project)
        self.assertIn("NSExtensionPointIdentifier", info)
        self.assertIn("NSExtensionAttributes", info)
        self.assertIn("NSExtensionActivationRule", info)
        self.assertIn("com.apple.share-services", info)
        self.assertIn("TRUEPREDICATE", info)
        self.assertIn("extensionContext?.open", share)
        self.assertIn("UIPasteboard.general.string", share)
        self.assertIn("HERMES_AGENT_SHARE_V1", share)
        self.assertIn("openContainingAppViaResponderChain", share)
        self.assertIn("NSSelectorFromString(\"openURL:\")", share)
        self.assertIn("UTType.url", share)
        self.assertIn("UTType.text", share)
        self.assertIn("HermesAgentSharePayload", share)
        self.assertIn("HermesAgentSharePayload", core)
        self.assertIn("host = \"share\"", core)
        self.assertIn("base_url=", core)
        self.assertIn("Share Extension", content)
        self.assertIn("Inbox", content)
        self.assertIn("No shared item received yet", content)
        self.assertIn("Shared item is ready", content)
        self.assertIn("Command Composer", content)
        self.assertIn("pendingShareCommandPrompt", content)
        self.assertIn("recoverShareCommandPromptFromPasteboard", content)
        self.assertIn("applyPendingShareCommandPrompt", content)
        self.assertIn("lastShareExtensionHandoff", content)
        self.assertIn("Last shared item: <redacted operator content>", content)
        self.assertNotIn("Text(lastShareExtensionHandoff", content, "share extension should not render raw shared content in chrome")

    def test_app_executes_live_gateway_calls_and_renders_response_state(self):
        content_file = ROOT / "App" / "ContentView.swift"
        content = content_file.read_text()
        self.assertIn("Execute Command Run", content)
        self.assertIn("executeCommandRun", content)
        self.assertIn("decideApproval", content)
        self.assertIn("GatewayClient", content)
        self.assertIn("Task {", content)
        self.assertIn("currentCommand", content)
        self.assertIn("currentDecision", content)
        self.assertIn("approval.reason", content)
        self.assertIn("run.currentStep", content)

    def test_app_has_stateful_cockpit_surfaces_for_history_refresh_and_results(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("Thread History", content)
        self.assertIn("Pending Approvals", content)
        self.assertIn("Refresh Pending Approvals", content)
        self.assertIn("threadMessages", content)
        self.assertIn("pendingApprovals", content)
        self.assertIn("refreshPendingApprovals", content)
        self.assertIn("loadThreadHistory", content)
        self.assertIn("resultMessage", content)
        self.assertIn("ThreadMessagesResponse", core)
        self.assertIn("PendingApprovalsResponse", core)
        self.assertIn("fetchPendingApprovals", core)
        self.assertIn("fetchThreadMessages", core)

    def test_core_has_hermes_api_server_adapter_seam_without_replacing_mock_gateway(self):
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        settings_file = ROOT / "App" / "GatewaySettings.swift"
        content_file = ROOT / "App" / "ContentView.swift"
        core = core_file.read_text()
        settings = settings_file.read_text()
        content = content_file.read_text()

        self.assertIn("HermesAPIEndpoint", core)
        self.assertIn("HermesAPIClient", core)
        self.assertIn("HermesRunSubmission", core)
        self.assertIn("HermesRunStatus", core)
        self.assertIn("HermesApprovalChoice", core)
        self.assertIn("/v1/capabilities", core)
        self.assertIn("/v1/runs", core)
        self.assertIn("/approval", core)
        self.assertIn("http://127.0.0.1:8642", settings)
        self.assertIn("hermesAPIServer", settings)
        self.assertIn("Hermes API", content)
        self.assertIn("Fetch Hermes API Capabilities", content)
        self.assertIn("Bearer token", content)
        self.assertIn("SecureField", content)
        self.assertIn("Run Live Hermes Smoke", content)
        self.assertIn("submitHermesSmokeRun", content)
        self.assertIn("HERMES_AGENT_IOS_LIVE_SMOKE_OK", core)
        self.assertIn("Run Live Approval Smoke", content)
        self.assertIn("submitHermesApprovalSmokeRun", content)
        self.assertIn("HermesLiveSmoke.approvalPrompt", content)
        self.assertIn("pollHermesApprovalSmokeStatus", content)
        self.assertIn("HermesLiveSmoke.approvalCard", content)
        self.assertIn("waiting_for_approval", content)
        self.assertIn("HERMES_AGENT_IOS_APPROVAL_SMOKE_OK", core)
        self.assertIn("/tmp/hermes-agent-ios-approval-smoke", core)
        self.assertIn("pollHermesRunStatus", content)
        self.assertIn("Hermes Events", content)
        self.assertIn("hermesRunEvents", content)
        self.assertIn("streamHermesRunEvents", content)
        self.assertIn("submitHermesRun", content)
        self.assertIn("hermesClient", content)

    def test_app_promotes_live_approval_request_events_to_cards_and_actions(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesApprovalCard", core)
        self.assertIn("HermesSSEEventBuffer", core)
        self.assertIn("onEvent", core)
        self.assertIn("cards(from", core)
        self.assertIn("patternKeys", core)
        self.assertIn("command", core)
        self.assertIn("Live Approval Cards", content)
        self.assertIn("hermesApprovalCards", content)
        self.assertIn("resolveHermesApproval", content)
        self.assertIn("isResolvingHermesApproval", content)
        self.assertIn("Approve Once", content)
        self.assertIn("Trust Session", content)
        self.assertIn("Always Allow", content)
        self.assertIn("Deny", content)
        self.assertIn("Risk", content)
        self.assertIn("Scope", content)
        self.assertIn("Rollback", content)
        self.assertIn("Reason", content)
        self.assertIn("riskLabel", content)

    def test_app_has_reusable_live_run_cockpit_cards_for_non_smoke_runs(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesRunCard", core)
        self.assertIn("isTerminal", core)
        self.assertIn("isWaitingForApproval", core)
        self.assertIn("updated(with", core)
        self.assertIn("Advanced · Live Run Details", content)
        self.assertIn("hermesRunCards", content)
        self.assertIn("upsertHermesRunCard", content)
        self.assertIn("Active Run", content)
        self.assertIn("Waiting for Approval", content)
        self.assertIn("Completed", content)
        self.assertIn("submitHermesRun", content)
        self.assertIn("HermesRunCard(submission", content)

    def test_general_live_run_cockpit_falls_back_to_polling_when_sse_stalls(self):
        content_file = ROOT / "App" / "ContentView.swift"
        content = content_file.read_text()

        self.assertIn("withRunEventStreamTimeout", content)
        self.assertIn("eventStreamTimeoutSeconds", content)
        self.assertIn("pollHermesRunStatus(runId: runId)", content)
        self.assertIn("Hermes event stream timed out; polling run status", content)
        self.assertIn("waiting_for_approval", content)
        self.assertIn("genericApprovalCard", content)
        self.assertIn("isWorking = false", content, "general run must release the global spinner after fallback polling")

    def test_live_run_cockpit_persists_run_card_history_locally(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("Codable", core)
        self.assertIn("hermesRunCardsJSON", content)
        self.assertIn("loadPersistedHermesRunCards", content)
        self.assertIn("persistHermesRunCards", content)
        self.assertIn("JSONEncoder.hermesAgentGateway.encode(hermesRunCards)", content)
        self.assertIn("JSONDecoder.hermesAgentGateway.decode([HermesRunCard].self", content)
        self.assertIn(".onAppear", content)
        self.assertIn("refreshNonTerminalHermesRunCards", content)

    def test_live_run_cockpit_surfaces_physical_run_state_affordances(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("operatorStateLabel", core)
        self.assertIn("operatorDetail", core)
        self.assertIn("lastCheckedLabel", core)
        self.assertIn("Refresh Run", content)
        self.assertIn("refreshHermesRunCard", content)
        self.assertIn("Last checked", content)
        self.assertIn("Polling run status", content)
        self.assertIn("Waiting for iPhone approval", content)
        self.assertIn("SSE fallback active", content)

    def test_live_run_cockpit_filters_and_prioritizes_operator_history(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesRunCardFilter", core)
        self.assertIn("needsAttention", core)
        self.assertIn("filteredAndPrioritized", core)
        self.assertIn("operatorSummary", core)
        self.assertIn("@State private var hermesRunCardFilter", content)
        self.assertIn("Run History Filter", content)
        self.assertIn("Needs Attention", content)
        self.assertIn("Active", content)
        self.assertIn("Completed", content)
        self.assertIn("filteredHermesRunCards", content)
        self.assertIn("ForEach(filteredHermesRunCards)", content)
        self.assertIn("Attention first", content)
        self.assertIn("Showing", content)

    def test_physical_device_debug_panel_surfaces_runtime_handoff_state(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesDeviceDiagnostics", core)
        self.assertIn("apiURLLabel", core)
        self.assertIn("tokenStateLabel", core)
        self.assertIn("capabilityCheckLabel", core)
        self.assertIn("handoffStateLabel", core)
        self.assertIn("Physical Device Debug", content)
        self.assertIn("lastHermesCapabilityCheck", content)
        self.assertIn("physicalDeviceDiagnostics", content)
        self.assertIn("Run Capability Check", content)
        self.assertIn("Current API URL", content)
        self.assertIn("Token", content)
        self.assertIn("Last capability check", content)
        self.assertIn("Wi‑Fi/CoreDevice", content)
        self.assertNotIn("Text(hermesBearerToken", content, "debug panel must not render the raw bearer token")

    def test_live_approval_audit_persists_operator_decision_context(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesApprovalAuditEntry", core)
        self.assertIn("decisionLabel", core)
        self.assertIn("contextSummary", core)
        self.assertIn("resultSummary", core)
        self.assertIn("approvalAuditJSON", content)
        self.assertIn("hermesApprovalAudit", content)
        self.assertIn("Approval Audit", content)
        self.assertIn("recordHermesApprovalAudit", content)
        self.assertIn("loadPersistedHermesApprovalAudit", content)
        self.assertIn("persistHermesApprovalAudit", content)
        self.assertIn("Decision", content)
        self.assertIn("Command", content)
        self.assertIn("Outcome", content)
        self.assertIn("Resolved at", content)
        self.assertIn("Audit trail", content)
        self.assertIn("JSONEncoder.hermesAgentGateway.encode(hermesApprovalAudit)", content)
        self.assertIn("JSONDecoder.hermesAgentGateway.decode([HermesApprovalAuditEntry].self", content)

    def test_on_device_operator_debug_log_records_actions_and_persists(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesOperatorLogEntry", core)
        self.assertIn("categoryLabel", core)
        self.assertIn("detailLabel", core)
        self.assertIn("operatorLogJSON", content)
        self.assertIn("operatorLogEntries", content)
        self.assertIn("Operator Debug Log", content)
        self.assertIn("recordOperatorLog", content)
        self.assertIn("loadPersistedOperatorLog", content)
        self.assertIn("persistOperatorLog", content)
        self.assertIn("Capability check", content)
        self.assertIn("Bootstrap", content)
        self.assertIn("Approval decision", content)
        self.assertIn("Run submitted", content)
        self.assertIn("JSONEncoder.hermesAgentGateway.encode(operatorLogEntries)", content)
        self.assertIn("JSONDecoder.hermesAgentGateway.decode([HermesOperatorLogEntry].self", content)
        self.assertNotIn("Text(hermesBearerToken", content, "operator log must not render raw bearer tokens")

    def test_unified_operator_timeline_filters_audit_and_debug_events(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesOperatorTimelineItem", core)
        self.assertIn("HermesOperatorTimelineFilter", core)
        self.assertIn("makeTimeline", core)
        self.assertIn("filteredTimeline", core)
        self.assertIn("timelineSummary", core)
        self.assertIn("@State private var operatorTimelineFilter", content)
        self.assertIn("Operator Timeline", content)
        self.assertIn("Timeline Filter", content)
        self.assertIn("Approvals", content)
        self.assertIn("Debug", content)
        self.assertIn("filteredOperatorTimeline", content)
        self.assertIn("ForEach(filteredOperatorTimeline)", content)
        self.assertIn("No timeline events match this filter", content)
        self.assertIn("Showing", content)
        self.assertNotIn("Text(hermesBearerToken", content, "operator timeline must not render raw bearer tokens")

    def test_operator_timeline_detail_view_surfaces_replay_context(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesOperatorTimelineDetail", core)
        self.assertIn("replayTitle", core)
        self.assertIn("contextDetail", core)
        self.assertIn("outcomeDetail", core)
        self.assertIn("@State private var selectedOperatorTimelineItemId", content)
        self.assertIn("selectedOperatorTimelineItem", content)
        self.assertIn("selectedOperatorTimelineDetail", content)
        self.assertIn("Timeline Detail", content)
        self.assertIn("Select Timeline Event", content)
        self.assertIn("Replay context", content)
        self.assertIn("Outcome detail", content)
        self.assertIn("No timeline event selected", content)
        self.assertIn("selectedOperatorTimelineItemId = item.id", content)
        self.assertNotIn("Text(hermesBearerToken", content, "timeline detail must not render raw bearer tokens")

    def test_operator_timeline_has_clear_copy_and_export_controls(self):
        content_file = ROOT / "App" / "ContentView.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesOperatorTimelineExport", core)
        self.assertIn("markdownSnapshot", core)
        self.assertIn("@State private var lastOperatorTimelineExport", content)
        self.assertIn("Copy Selected Event", content)
        self.assertIn("Export Timeline Snapshot", content)
        self.assertIn("Clear Timeline History", content)
        self.assertIn("copySelectedTimelineEvent", content)
        self.assertIn("exportOperatorTimelineSnapshot", content)
        self.assertIn("clearOperatorTimelineHistory", content)
        self.assertIn("UIPasteboard.general.string", content)
        self.assertIn("Timeline export ready", content)
        self.assertIn("operatorLogEntries = []", content)
        self.assertIn("hermesApprovalAudit = []", content)
        self.assertNotIn("Text(hermesBearerToken", content, "timeline controls must not render raw bearer tokens")

    def test_dynamic_island_live_activity_contract_is_wired(self):
        project_file = ROOT / "project.yml"
        app_info_file = ROOT / "App" / "Info.plist"
        content_file = ROOT / "App" / "ContentView.swift"
        app_file = ROOT / "App" / "HermesAgentIOSApp.swift"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        widget_file = ROOT / "LiveActivityWidget" / "HermesAgentLiveActivityWidget.swift"
        widget_info_file = ROOT / "LiveActivityWidget" / "Info.plist"
        project = project_file.read_text()
        app_info = app_info_file.read_text()
        content = content_file.read_text()
        app = app_file.read_text()
        core = core_file.read_text()

        self.assertIn("Hermes Agent Live Activity", project)
        self.assertIn("app-extension", project)
        self.assertIn("com.tinyleed.hermes-agent-ios.live-activity", project)
        self.assertIn("NSSupportsLiveActivities", app_info)
        self.assertIn("HermesAgentLiveActivitySnapshot", core)
        self.assertIn("HermesAgentLiveActivityAttributes", core)
        self.assertIn("Live Activity / Dynamic Island", content)
        self.assertIn("activityAuthorizationInfo", content)
        self.assertIn("startOrUpdateLiveActivity", content)
        self.assertIn("autoStartLiveActivityForWaitingApproval", content)
        self.assertIn("await autoStartLiveActivityForWaitingApproval()", content)
        self.assertIn("Live approval smoke waiting; Dynamic Island", content)
        self.assertIn("updateLiveActivityAfterApprovalResolution", content)
        self.assertIn("updated after approval", content)
        self.assertIn("ending automatically", content)
        self.assertIn("Start Island Diagnostic", content)
        self.assertIn("startDynamicIslandDiagnosticActivity", content)
        self.assertIn("background app, check compact island", content)
        self.assertIn("Notification Readiness", content)
        self.assertIn("Request Local Notification Permission", content)
        self.assertIn("Run Local Approval Notification", content)
        self.assertIn("Apple Developer Program enrollment required", core)
        self.assertIn("NotificationReadinessState", core)
        self.assertIn("NotificationTokenRegistrationPayload", core)
        self.assertIn("APNsApprovalNotificationPayload", core)
        self.assertIn("registerNotificationToken", core)
        self.assertIn("/v0/notification-tokens", core)
        self.assertIn("UNUserNotificationCenter", content)
        self.assertIn("UNUserNotificationCenterDelegate", app)
        self.assertIn("@UIApplicationDelegateAdaptor", app)
        self.assertIn("UNUserNotificationCenter.current().delegate = self", app)
        self.assertIn("willPresent notification", app)
        self.assertIn(".banner", app)
        self.assertIn(".list", app)
        self.assertIn("Local proof only", content)
        self.assertIn("foreground banner enabled", content)
        self.assertNotIn("registerForRemoteNotifications", content, "Personal Team lane should not attempt real APNs device-token registration yet")
        self.assertIn("finalSnapshot", content)
        self.assertIn("shouldEndLiveActivityAfterUpdate", core)
        self.assertIn("dynamicIslandLeadingLabel", core)
        self.assertIn("dynamicIslandTrailingLabel", core)
        self.assertIn("OK?", core)
        self.assertIn("Approved and completed", core)
        self.assertIn("Paused for approval", core)
        self.assertIn("Run failed", core)
        self.assertIn("endLiveActivity", content)
        self.assertIn("Dynamic Island status", content)
        self.assertTrue(widget_file.exists(), "Widget extension source should exist")
        self.assertTrue(widget_info_file.exists(), "Widget extension Info.plist should exist")
        widget = widget_file.read_text()
        widget_info = widget_info_file.read_text()
        self.assertIn("ActivityConfiguration", widget)
        self.assertIn("DynamicIsland", widget)
        self.assertIn("compactLeading", widget)
        self.assertIn("compactTrailing", widget)
        self.assertIn("minimal", widget)
        self.assertIn("dynamicIslandCompactLeadingLabel", widget)
        self.assertIn("dynamicIslandCompactTrailingLabel", widget)
        self.assertIn("foregroundStyle(context.state.state == .waitingForApproval ? .orange : .cyan)", widget)
        self.assertIn("HermesAgentLiveActivityAttributes", widget)
        self.assertIn("com.apple.widgetkit-extension", widget_info)

    def test_simulator_bootstrap_script_injects_live_hermes_settings_without_printing_secret(self):
        bootstrap = ROOT / "scripts" / "bootstrap_simulator_hermes_api.sh"
        self.assertTrue(bootstrap.exists(), "simulator bootstrap should exist")
        text = bootstrap.read_text()

        self.assertIn("API_SERVER_KEY", text)
        self.assertIn("API_SERVER_PORT", text)
        self.assertIn("read_env_var", text)
        self.assertIn("SIMULATOR_API_SERVER_HOST", text)
        self.assertIn("0.0.0.0", text)
        self.assertIn("127.0.0.1", text)
        self.assertNotIn("source \"$ENV_FILE\"", text)
        self.assertIn("xcrun simctl spawn", text)
        self.assertIn("defaults write com.tinyleed.hermes-agent-ios hermesAPIBaseURL", text)
        self.assertIn("defaults write com.tinyleed.hermes-agent-ios hermesBearerToken", text)
        self.assertIn("HERMES_GATEWAY_WS_URL", text)
        self.assertIn("HERMES_GATEWAY_WS_TOKEN", text)
        self.assertIn("HERMES_DESKTOP_REMOTE_URL", text)
        self.assertIn("HERMES_DESKTOP_REMOTE_TOKEN", text)
        self.assertIn("HERMES_AGENT_IOS_HERMES_GATEWAY_BASE_URL", text)
        self.assertIn("defaults write com.tinyleed.hermes-agent-ios hermesGatewayRemoteBaseURL", text)
        self.assertIn("defaults write com.tinyleed.hermes-agent-ios hermesGatewayWebSocketURL", text)
        self.assertIn("defaults write com.tinyleed.hermes-agent-ios hermesGatewayWebSocketToken", text)
        self.assertIn("defaults delete com.tinyleed.hermes-agent-ios hermesGatewayWebSocketURL", text)
        self.assertNotIn("echo $API_SERVER_KEY", text)
        self.assertNotIn("printf '%s' \"$API_SERVER_KEY\"", text)

    def test_apns_sender_skeleton_renders_secret_free_approval_payload(self):
        script = ROOT / "scripts" / "render_apns_approval_payload.py"
        self.assertTrue(script.exists(), "APNs approval payload renderer should exist before Developer Program enrollment")
        text = script.read_text()

        self.assertIn("Hermes Agent approval required", text)
        self.assertIn("hermes-agent-ios://approval/", text)
        self.assertIn("thread-id", text)
        self.assertNotIn(".p8", text)
        self.assertNotIn("PRIVATE_KEY", text)
        self.assertNotIn("secret", text.lower())

    def test_launch_script_bootstraps_live_hermes_settings_before_app_launch(self):
        launch = ROOT / "scripts" / "launch_simulator.sh"
        self.assertTrue(launch.exists(), "launch script should exist")
        text = launch.read_text()

        self.assertIn("bootstrap_simulator_hermes_api.sh", text)
        self.assertLess(text.index("bootstrap_simulator_hermes_api.sh"), text.index("simctl launch"))

    def test_app_accepts_physical_device_bootstrap_deep_link(self):
        content_file = ROOT / "App" / "ContentView.swift"
        info_file = ROOT / "App" / "Info.plist"
        core_file = ROOT / "Sources" / "HermesAgentCore" / "HermesAgentCore.swift"
        content = content_file.read_text()
        info = info_file.read_text()
        core = core_file.read_text()

        self.assertIn("HermesDeviceBootstrapLink", core)
        self.assertIn("hermes-agent-ios", core)
        self.assertIn("base_url", core)
        self.assertIn("token", core)
        self.assertIn("gateway_base_url", core)
        self.assertIn("gateway_ws_token", core)
        self.assertIn("gatewayRemoteBaseURL", core)
        self.assertIn("gatewayWebSocketToken", core)
        self.assertIn("hermesGatewayRemoteBaseURLString", content)
        self.assertIn("hermesGatewayWebSocketToken", content)
        self.assertIn("Physical-device Hermes chat bootstrap applied", content)
        self.assertIn("Physical Device Bootstrap", content)
        self.assertIn("applyHermesBootstrapURL", content)
        self.assertIn("onOpenURL", content)
        self.assertIn("CFBundleURLTypes", info)
        self.assertIn("hermes-agent-ios", info)
        self.assertIn("NSAllowsArbitraryLoads", info)
        self.assertIn("NSExceptionDomains", info)
        self.assertNotIn("taileb", info)
        self.assertIn("NSExceptionAllowsInsecureHTTPLoads", info)

    def test_physical_device_bootstrap_script_creates_secret_bearing_artifact_without_printing_token(self):
        script = ROOT / "scripts" / "create_physical_device_bootstrap_link.sh"
        self.assertTrue(script.exists(), "physical device bootstrap script should exist")
        text = script.read_text()

        self.assertIn("API_SERVER_KEY", text)
        self.assertIn("HERMES_API_PUBLIC_BASE_URL", text)
        self.assertIn("HERMES_DESKTOP_REMOTE_URL", text)
        self.assertIn("HERMES_DESKTOP_REMOTE_TOKEN", text)
        self.assertIn("gateway_base_url", text)
        self.assertIn("gateway_ws_token", text)
        self.assertIn("Gateway token: <redacted>", text)
        self.assertIn("hermes-agent-ios://hermes-api", text)
        self.assertIn("bootstrap_url", text)
        self.assertIn("bootstrap.html", text)
        self.assertIn("qrencode", text)
        self.assertNotIn("echo $API_SERVER_KEY", text)
        self.assertNotIn("printf '%s' \"$API_SERVER_KEY\"", text)
        self.assertIn("Bearer token: <redacted>", text)

    def test_lan_readiness_script_verifies_hermes_api_without_printing_secret(self):
        script = ROOT / "scripts" / "verify_hermes_api_lan.sh"
        self.assertTrue(script.exists(), "LAN readiness verification script should exist")
        text = script.read_text()

        self.assertIn("API_SERVER_KEY", text)
        self.assertIn("/v1/capabilities", text)
        self.assertIn("ipconfig getifaddr", text)
        self.assertIn("curl", text)
        self.assertIn("HERMES_API_PUBLIC_BASE_URL", text)
        self.assertIn("Bearer token: <redacted>", text)
        self.assertIn("LAN Hermes API reachable", text)
        self.assertIn("${HERMES_API_PUBLIC_BASE_URL:-", text, "operator-provided LAN URL must override stale .env public URLs after Wi-Fi/IP changes")
        self.assertNotIn("echo $API_SERVER_KEY", text)
        self.assertNotIn("printf '%s' \"$API_SERVER_KEY\"", text)

    def test_physical_device_handoff_script_checks_signing_device_lan_and_artifacts(self):
        script = ROOT / "scripts" / "prepare_physical_device_handoff.sh"
        self.assertTrue(script.exists(), "physical-device handoff script should exist")
        text = script.read_text()

        self.assertIn("xcrun xctrace list devices", text)
        self.assertIn("xcrun devicectl list devices", text)
        self.assertIn("verify_hermes_api_lan.sh", text)
        self.assertIn("create_physical_device_bootstrap_link.sh", text)
        self.assertIn("xcodebuild", text)
        self.assertIn("CODE_SIGNING_ALLOWED=YES", text)
        self.assertIn("ENABLE_DEBUG_DYLIB=NO", text)
        self.assertIn("-allowProvisioningUpdates", text)
        self.assertIn("HERMES_AGENT_IOS_DEVELOPMENT_TEAM", text)
        self.assertIn("project.yml", text)
        self.assertIn("DEVELOPMENT_TEAM:", text)
        self.assertIn("Devices Offline", text)
        self.assertIn("in_offline_devices", text)
        self.assertIn("errSecInteractionNotAllowed", text)
        self.assertIn("Always Allow", text)
        self.assertIn("keychain", text.lower())
        self.assertIn("physical iPhone", text)
        self.assertIn("bootstrap.html", text)
        self.assertIn("[0-9A-Fa-f-]{24,40}", text, "device detection should accept modern physical iPhone UDIDs, not only UUID-form identifiers")
        self.assertNotIn("echo $API_SERVER_KEY", text)
        self.assertNotIn("printf '%s' \"$API_SERVER_KEY\"", text)

    def test_physical_device_aqua_signing_runner_delegates_build_to_terminal_session(self):
        script = ROOT / "scripts" / "run_physical_device_build_in_aqua.sh"
        self.assertTrue(script.exists(), "Aqua signing runner should exist for Hermes-driven physical-device builds")
        text = script.read_text()

        self.assertIn("Terminal", text)
        self.assertIn("osascript", text)
        self.assertIn("prepare_physical_device_handoff.sh", text)
        self.assertIn("HERMES_AGENT_IOS_DEVELOPMENT_TEAM", text)
        self.assertIn("DEVELOPMENT_TEAM", text)
        self.assertIn("aqua-signing-runner", text)
        self.assertIn("physical-device-build.log", text)
        self.assertIn("codesign --verify --deep --strict", text)
        self.assertIn("HERMES_API_PUBLIC_BASE_URL", text)
        self.assertIn("HERMES_AGENT_IOS_DEVICE_ID", text)
        self.assertIn("<configured>", text)
        self.assertNotIn("API_SERVER_KEY", text)
        self.assertNotIn("cat /tmp/hermes-agent-ios/bootstrap.url", text)

    def test_physical_device_install_launch_script_uses_payload_url_and_redacts_secret_output(self):
        script = ROOT / "scripts" / "install_launch_physical_device.sh"
        self.assertTrue(script.exists(), "physical-device install/launch script should exist after a signed build")
        text = script.read_text()

        self.assertIn("xcrun devicectl device install app", text)
        self.assertIn("xcrun devicectl list devices", text)
        self.assertIn("xcrun devicectl device process launch", text)
        self.assertIn("--payload-url", text, "bootstrap URL should be passed as a payload URL, not as a raw argv value")
        self.assertIn("bootstrap.url", text)
        self.assertIn("device-install.json", text)
        self.assertIn("device-launch.json", text)
        self.assertIn("redact_log", text)
        self.assertIn("Bearer token: <redacted>", text)
        self.assertIn("Devices Offline", text)
        self.assertIn("in_offline_devices", text)
        self.assertIn("first_physical_iphone_id || true", text)
        self.assertNotIn(' -- "$BOOTSTRAP_URL"', text)
        self.assertNotIn("cat /tmp/hermes-agent-ios/bootstrap.url", text)
        self.assertNotIn("echo $BOOTSTRAP_URL", text)
        self.assertNotIn("echo $API_SERVER_KEY", text)


if __name__ == "__main__":
    unittest.main()
